### ISSUE TITLE
ensure-yaml-patch failed

### ISSUE THREAD

**Issue by zhujian7** [openshift/build-machinery-go#56]
GitHub action failed with:
```
curl -s -f -L https://github.com/krishicks/yaml-patch/releases/download/v0.0.10/yaml_patch_linux -o '_output/tools/bin/yaml-patch'
make: *** [vendor/github.com/openshift/build-machinery-go/make/targets/openshift/../../targets/openshift/yaml-patch.mk:11: ensure-yaml-patch] Error 22
```

in [yaml-patch.mk](https://github.com/openshift/build-machinery-go/blob/master/make/targets/openshift/yaml-patch.mk#L18) we get yaml-patch from `https://github.com/krishicks/yaml-patch`:
```
curl -s -f -L https://github.com/krishicks/yaml-patch/releases/download/$(YAML_PATCH_VERSION)/yaml_patch_$(GOHOSTOS) -o '$(YAML_PATCH)'
```
but the repo is not available now:
![image](https://user-images.githubusercontent.com/36154065/145771252-ffb398e6-9d4c-4602-b858-7843f37fc290.png)

**Comment by soltysh** [comment]
This was already fixed in #58.
/close
